/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { ThreatAssessment } from '../types';
import { ThreatGauge } from './ThreatGauge';
import { RiskBreakdownView } from './RiskBreakdownView';
import { EvidenceSection } from './EvidenceSection';
import { RecommendationPanel } from './RecommendationPanel';
import { VerificationChecklistView } from './VerificationChecklistView';
import { 
  ShieldAlert, 
  ArrowLeft, 
  Download, 
  Copy, 
  Check, 
  Building2, 
  User, 
  DollarSign, 
  Globe, 
  Clock, 
  FileText, 
  AlertTriangle,
  ExternalLink,
  ShieldCheck,
  Share2
} from 'lucide-react';

interface ResultScreenProps {
  assessment: ThreatAssessment;
  onNewScan: () => void;
  onViewDashboard: () => void;
}

export const ResultScreen: React.FC<ResultScreenProps> = ({
  assessment,
  onNewScan,
  onViewDashboard,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopyReport = () => {
    const reportSummary = `OFFERGUARD AI THREAT REPORT
==================================================
Target: ${assessment.targetSummary}
Input Type: ${assessment.inputType.toUpperCase()}
Date: ${new Date(assessment.createdAt).toLocaleString()}
Scam Threat Index: ${assessment.threatScore} / 100 (${assessment.riskLevel})
Confidence: ${assessment.confidence}%
Verdict: ${assessment.verdictHeadline}

EXECUTIVE SUMMARY:
${assessment.summary}

DETECTED RISK SIGNALS (${assessment.signals.length}):
${assessment.signals.map(s => `- [${s.severity}] ${s.title}: "${s.evidence}" (${s.explanation})`).join('\n')}

WHAT TO DO NEXT:
${assessment.recommendations.map(r => `• ${r}`).join('\n')}

LIMITATIONS:
${assessment.limitations.join('; ')}
==================================================
Generated by OFFERGUARD AI - Verify Before You Trust`;

    navigator.clipboard.writeText(reportSummary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadReport = () => {
    const reportText = `OFFERGUARD AI THREAT REPORT
==================================================
Target: ${assessment.targetSummary}
Input Type: ${assessment.inputType.toUpperCase()}
Date: ${new Date(assessment.createdAt).toLocaleString()}
Threat Score: ${assessment.threatScore}/100 (${assessment.riskLevel})
Confidence: ${assessment.confidence}%

SUMMARY:
${assessment.summary}

RISK BREAKDOWN:
- Payment Risk: ${assessment.breakdown.paymentRisk.score}/100 (${assessment.breakdown.paymentRisk.severity})
- Phishing Risk: ${assessment.breakdown.phishingRisk.score}/100 (${assessment.breakdown.phishingRisk.severity})
- Impersonation Risk: ${assessment.breakdown.impersonationRisk.score}/100 (${assessment.breakdown.impersonationRisk.severity})
- Urgency Risk: ${assessment.breakdown.urgencyRisk.score}/100 (${assessment.breakdown.urgencyRisk.severity})
- Credential Risk: ${assessment.breakdown.credentialRisk.score}/100 (${assessment.breakdown.credentialRisk.severity})
- URL Risk: ${assessment.breakdown.urlRisk.score}/100 (${assessment.breakdown.urlRisk.severity})
- Domain Risk: ${assessment.breakdown.domainRisk.score}/100 (${assessment.breakdown.domainRisk.severity})
- Social Engineering: ${assessment.breakdown.socialEngineeringRisk.score}/100 (${assessment.breakdown.socialEngineeringRisk.severity})

DETECTED SIGNALS:
${assessment.signals.map(s => `[${s.severity}] ${s.title}\nEvidence: "${s.evidence}"\nExplanation: ${s.explanation}\n`).join('\n')}

RECOMMENDED ACTIONS:
${assessment.recommendations.map(r => `• ${r}`).join('\n')}

VERIFICATION STEPS:
${assessment.verificationSteps.map(v => `[${v.priority}] ${v.title}: ${v.instruction}`).join('\n')}

LIMITATIONS:
${assessment.limitations.join('\n')}
`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `OfferGuard-Report-${assessment.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8 animate-fadeIn">
      
      {/* Top Breadcrumb & Action Controls */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <button
          onClick={onNewScan}
          className="inline-flex items-center gap-2 text-xs font-mono text-cyan-400 hover:text-cyan-300 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>INSPECT ANOTHER OFFER</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyReport}
            className="px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-mono text-slate-300 transition-colors flex items-center gap-1.5"
            title="Copy Report to Clipboard"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Summary'}</span>
          </button>

          <button
            onClick={handleDownloadReport}
            className="px-3 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-mono text-slate-300 transition-colors flex items-center gap-1.5"
            title="Download Full Report"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download TXT</span>
          </button>

          <button
            onClick={onViewDashboard}
            className="px-3 py-1.5 rounded-lg bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-500/40 text-xs font-mono text-cyan-300 transition-colors"
          >
            View Dashboard
          </button>
        </div>
      </div>

      {/* Demo Analysis Warning Banner if applicable */}
      {assessment.isDemo && (
        <div className="rounded-xl bg-amber-950/40 border border-amber-600/40 p-3.5 flex items-center gap-3 text-xs font-mono text-amber-200">
          <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0" />
          <div className="flex-1">
            <strong className="text-amber-300 font-bold uppercase tracking-wider mr-2">
              [DEMO ANALYSIS]:
            </strong>
            This assessment is a simulated reference dataset demonstrating OfferGuard AI scoring architecture. Results do not represent real-time intelligence for live job applicants.
          </div>
        </div>
      )}

      {/* Primary Threat Header Bento */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Threat Gauge Component */}
        <div className="lg:col-span-1">
          <ThreatGauge
            score={assessment.threatScore}
            riskLevel={assessment.riskLevel}
            confidence={assessment.confidence}
          />
        </div>

        {/* Executive Verdict & Extracted Profile Card */}
        <div className="lg:col-span-2 rounded-2xl bg-slate-900/60 border border-slate-800 p-6 backdrop-blur-sm flex flex-col justify-between">
          <div>
            <div className="flex flex-wrap items-center gap-2 mb-3">
              <span className="px-2 py-0.5 rounded text-[11px] font-mono font-bold bg-slate-950 border border-slate-800 text-slate-300 uppercase">
                {assessment.inputType.toUpperCase()} ANALYSIS
              </span>
              <span className="text-xs font-mono text-slate-500">
                {new Date(assessment.createdAt).toLocaleDateString()} • {assessment.processingTimeMs}ms execution
              </span>
            </div>

            <h2 className="text-xl sm:text-2xl font-bold font-mono tracking-tight text-slate-100 mb-2">
              {assessment.targetSummary}
            </h2>

            <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80 mb-4">
              <p className="text-xs sm:text-sm text-cyan-200/90 font-mono font-medium leading-relaxed">
                {assessment.verdictHeadline}
              </p>
              <p className="text-xs text-slate-400 mt-2 font-sans leading-relaxed">
                {assessment.summary}
              </p>
            </div>
          </div>

          {/* Extracted Entities Chips */}
          <div className="pt-3 border-t border-slate-800/80">
            <div className="text-[11px] font-mono text-slate-400 uppercase tracking-wider mb-2">
              EXTRACTED OFFER ENTITIES:
            </div>
            <div className="flex flex-wrap gap-2 text-xs font-mono">
              {assessment.entities.companyName && (
                <div className="px-2.5 py-1 rounded-md bg-slate-950 border border-slate-800 text-slate-300 flex items-center gap-1.5">
                  <Building2 className="w-3.5 h-3.5 text-cyan-400" />
                  <span>{assessment.entities.companyName}</span>
                </div>
              )}
              {assessment.entities.jobTitle && (
                <div className="px-2.5 py-1 rounded-md bg-slate-950 border border-slate-800 text-slate-300 flex items-center gap-1.5">
                  <FileText className="w-3.5 h-3.5 text-cyan-400" />
                  <span>{assessment.entities.jobTitle}</span>
                </div>
              )}
              {assessment.entities.recruiterName && (
                <div className="px-2.5 py-1 rounded-md bg-slate-950 border border-slate-800 text-slate-300 flex items-center gap-1.5">
                  <User className="w-3.5 h-3.5 text-cyan-400" />
                  <span>{assessment.entities.recruiterName}</span>
                </div>
              )}
              {assessment.entities.statedCompensation && (
                <div className="px-2.5 py-1 rounded-md bg-slate-950 border border-slate-800 text-slate-300 flex items-center gap-1.5">
                  <DollarSign className="w-3.5 h-3.5 text-emerald-400" />
                  <span>{assessment.entities.statedCompensation}</span>
                </div>
              )}
              {assessment.entities.paymentDemands && assessment.entities.paymentDemands.length > 0 && (
                <div className="px-2.5 py-1 rounded-md bg-red-950/60 border border-red-800/50 text-red-200 flex items-center gap-1.5">
                  <AlertTriangle className="w-3.5 h-3.5 text-red-400" />
                  <span>Fee: {assessment.entities.paymentDemands[0]}</span>
                </div>
              )}
            </div>
          </div>

        </div>

      </div>

      {/* Observable URL Intelligence Section (if URL was inspected or detected) */}
      {assessment.urlAnalysis && (
        <div className="rounded-2xl bg-slate-900/60 border border-slate-800 p-6 backdrop-blur-sm">
          <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-800/80">
            <div className="flex items-center gap-2">
              <Globe className="w-5 h-5 text-cyan-400" />
              <h3 className="text-base font-bold font-mono tracking-wide text-slate-100 uppercase">
                OBSERVABLE URL INFRASTRUCTURE INSPECTION
              </h3>
            </div>
            <span className="text-[11px] font-mono text-cyan-400 bg-cyan-950/50 border border-cyan-500/30 px-2 py-0.5 rounded">
              PASSIVE STRUCTURE CHECK
            </span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-mono">
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-slate-500 block text-[10px]">HOSTNAME</span>
              <span className="text-slate-200 font-bold truncate block">{assessment.urlAnalysis.hostname}</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-slate-500 block text-[10px]">ENCRYPTION (HTTPS)</span>
              <span className={assessment.urlAnalysis.isHttps ? 'text-emerald-400 font-bold' : 'text-red-400 font-bold'}>
                {assessment.urlAnalysis.isHttps ? 'Valid HTTPS' : 'Insecure HTTP'}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-slate-500 block text-[10px]">TLD RISK (.${assessment.urlAnalysis.tld})</span>
              <span className={assessment.urlAnalysis.isSuspiciousTld ? 'text-red-400 font-bold' : 'text-slate-200 font-bold'}>
                {assessment.urlAnalysis.isSuspiciousTld ? 'High-Abuse TLD' : 'Standard Enterprise TLD'}
              </span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-slate-500 block text-[10px]">DOMAIN AGE STATUS</span>
              <span className="text-slate-400 italic block">{assessment.urlAnalysis.domainAgeStatus}</span>
            </div>
          </div>
        </div>
      )}

      {/* Multidimensional Risk Matrix */}
      <RiskBreakdownView breakdown={assessment.breakdown} />

      {/* Evidence Section: WHY THIS WAS FLAGGED */}
      <EvidenceSection signals={assessment.signals} />

      {/* What You Should Do Next */}
      <RecommendationPanel 
        recommendations={assessment.recommendations} 
        riskLevel={assessment.riskLevel} 
      />

      {/* Candidate Verification Due Diligence Checklist */}
      <VerificationChecklistView tasks={assessment.verificationSteps} />

      {/* Limitations Disclaimer */}
      <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800 text-xs font-mono text-slate-500 space-y-1">
        <div className="font-bold text-slate-400 uppercase tracking-wider text-[11px]">
          ANALYTICAL SCOPE & LIMITATIONS:
        </div>
        <ul className="list-disc list-inside space-y-0.5">
          {assessment.limitations.map((lim, idx) => (
            <li key={idx}>{lim}</li>
          ))}
        </ul>
      </div>

    </div>
  );
};
